[package]
name = "blueprint-engine-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Starlark parser for Blueprint3"

[dependencies]
blueprint-engine-core.workspace = true
blueprint-starlark.workspace = true
blueprint-starlark-syntax.workspace = true
