[package]
name = "blueprint_parser"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Starlark parser for Blueprint3"

[dependencies]
blueprint_core.workspace = true
starlark.workspace = true
starlark_syntax.workspace = true
